GET http://localhost:3000/news

###

POST http://localhost:3000/news
Content-Type: application/json

{
    "title": "TEST 192_1_2",
    "text": "Текст новини",
    "img": "",
    "isActive": 0,
    "author_id": 1
}

###
DELETE http://localhost:3000/news

###
GET http://localhost:3000/news/320

###
 PUT http://localhost:3000/news/1
Content-Type: application/json

{
    "title": "UPDATE NEWS",
    "img": "PATH_2"
}
 
###

DELETE http://localhost:3000/news/200
